// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEyjwEjvT97iTNe10KoN6LO4Xwg9Ko4DM',
    appId: '1:839599387753:web:1d8c45cdab1f6839709ef8',
    messagingSenderId: '839599387753',
    projectId: 'fir-e-s-df310',
    authDomain: 'fir-e-s-df310.firebaseapp.com',
    storageBucket: 'fir-e-s-df310.firebasestorage.app',
    measurementId: 'G-0QW4MH5N9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-5C4FNjtNbujtV503GiD-SOpyRdvcjE',
    appId: '1:839599387753:android:3bdffac714608af4709ef8',
    messagingSenderId: '839599387753',
    projectId: 'fir-e-s-df310',
    storageBucket: 'fir-e-s-df310.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ZpeidbspNJzIz5cWst5jVt0_9gQvD4k',
    appId: '1:839599387753:ios:ea60abf97fd897e4709ef8',
    messagingSenderId: '839599387753',
    projectId: 'fir-e-s-df310',
    storageBucket: 'fir-e-s-df310.firebasestorage.app',
    iosClientId: '839599387753-982q08hat6ft8hse1qgh1e1ebs01q85e.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ZpeidbspNJzIz5cWst5jVt0_9gQvD4k',
    appId: '1:839599387753:ios:ea60abf97fd897e4709ef8',
    messagingSenderId: '839599387753',
    projectId: 'fir-e-s-df310',
    storageBucket: 'fir-e-s-df310.firebasestorage.app',
    iosClientId: '839599387753-982q08hat6ft8hse1qgh1e1ebs01q85e.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEyjwEjvT97iTNe10KoN6LO4Xwg9Ko4DM',
    appId: '1:839599387753:web:4b9ee2d1382c9685709ef8',
    messagingSenderId: '839599387753',
    projectId: 'fir-e-s-df310',
    authDomain: 'fir-e-s-df310.firebaseapp.com',
    storageBucket: 'fir-e-s-df310.firebasestorage.app',
    measurementId: 'G-2VZKWSRDJ1',
  );

}